/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Module: {
            id: string;
            title: string;
            lessons: string[];
            description?: string;
            instructor?: string;
        };
        Lesson: {
            id: string;
            title: string;
            content: string;
            durationMinutes?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
