name: OIDC Debug

on:
  workflow_dispatch: # run manually from the Actions tab

jobs:
  inspect-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request OIDC token and print claims
        run: |
          echo "Requesting OIDC token from GitHub..."
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')

          echo "=== Decoded OIDC token claims ==="
          echo "$TOKEN" | cut -d '.' -f 2 | base64 -d 2>/dev/null | jq
