 to migrate backend state"
git push origin main
name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Checks (dev)
    runs-on: ubuntu-latest

    env:
      TF_VAR_env: dev   # Automatically sets var.env

    defaults:
      run:
        working-directory: terraform/environments/dev  # Where your .tf files live

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Backend migration enabled here
      - name: Terraform Init (migrate state)
        run: terraform init -migrate-state

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
