name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # allows manual runs from the Actions tab

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, staging]  # add prod here if needed

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_env: ${{ matrix.environment }}
      TF_VAR_aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug AWS vars (no secrets printed)
        run: |
          if [ -z "${AWS_ACCESS_KEY_ID}" ]; then
            echo "❌ AWS_ACCESS_KEY_ID is NOT set"
            exit 1
          else
            echo "✅ AWS_ACCESS_KEY_ID is set"
          fi
          if [ -z "${AWS_SECRET_ACCESS_KEY}" ]; then
            echo "❌ AWS_SECRET_ACCESS_KEY is NOT set"
            exit 1
          else
            echo "✅ AWS_SECRET_ACCESS_KEY is set"
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8 # match your local version

      - name: Terraform Init
        run: ./tf.sh ${{ matrix.environment }} init

      - name: Terraform Plan
        run: ./tf.sh ${{ matrix.environment }} plan

      # Uncomment to auto-apply on main branch
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: ./tf.sh ${{ matrix.environment }} apply -auto-approve
