name: Terraform
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (e.g., dev, staging, prod)'
        required: true
      command:
        description: 'Terraform command (init, plan, apply, destroy)'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for OIDC
      contents: read     # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/terraform-ci-oidc
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5   # or your preferred version

      - name: Run Terraform
        run: |
          terraform -chdir="terraform/environments/${{ github.event.inputs.environment }}" \
            ${{ github.event.inputs.command }}
