name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for GitHub OIDC
      contents: read    # Required for actions/checkout

    steps:
      # 1. Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::016592542442:role/CybAcadGitHubActionsRole
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # 3. (Optional) Verify AWS identity
      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # 4. Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8 # or your required version

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init -migrate-state

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
